# Configuration file for MixSaT project - TEST specific

[paths]
SoccerNet_path = "/hdda/Datasets/SoccerNet/video"
ckpt_path = "MixSaT/2va8vsd7/checkpoints/epoch=9-step=5140.ckpt" # Path to the checkpoint for testing

[trainer]
deterministic = false
benchmark = true
precision = 'bf16'
sync_batchnorm = true
log_every_n_steps = 10
seed = 3407
test_only = true # Crucial for test mode

[data]
test_batch_size = 1
batch_size = 1024 # only affect testing batch size, large batch size can make testing faster
features = "baidu_soccer_embeddings.npy"
split_train = ["train"] # May not be strictly needed for test_only if dataloaders are conditional
split_valid = ["valid"] # May not be strictly needed for test_only if dataloaders are conditional
split_test = ["test", "challenge"] # Ensure this is the target split for testing/prediction
# max_num_worker: Calculated in main.py if not specified
# max_num_worker = 4 
framerate = 1
window_size = 3
window_shift = 0
window_stride = 0
version = 2 # Dataset version

[model]
feature_dim = '' 
NMS_window = 6
NMS_threshold = 0.0
num_classes = 18 # Assuming this is fixed, should be in train.toml too

[loss]
criterion = "BinaryFocalLoss"
weight = ""

[model_twins_svt]
s1_next_dim = 60
s1_patch_size = 8
s1_local_patch_size = 16
s1_global_k = 20
s1_depth = 1
s2_next_dim = 720
s2_patch_size = 4
s2_local_patch_size = 4
s2_global_k = 20
s2_depth = 2
peg_kernel_size = 9
dropout = 0.0
Post_norm = false

# Logger section - configure as needed for test runs
[logger]
logger_type = "wandb" # or "tensorboard" or "none"
project = "MixSaT_Train_2025" # Your WandB project name for test runs
entity = "cihe-cis"    # Your WandB entity (username or team)

# It's good practice to ensure all keys expected by main_logic are present,
# even if some are not actively used in test_only mode, to prevent hasattr/KeyError issues.
# Add any other necessary parameters that LitModel or LitDataModule might expect during instantiation,
# even if they are not used for the actual test pass.
# For example, if LitModel's __init__ expects args.some_training_param, it should be here.

[experiment_params] # Example, if you had such a section
accelerator = "gpu" # "gpu" or "cpu"
devices = "auto" # e.g., 1, "0,1", "auto", -1
strategy = "auto" # e.g., "ddp", "dp", "auto"

# Ensure all parameters required by the classes in main.py are present.
# For example, if `OutputManagementCallback` or other callbacks need specific args,
# they should be here.

# Output directory configuration
[output_dirs]
output_dir = "MixSaT_Test_2025"  # Single directory for all test outputs

# fast_dev_run can be useful for quick test script debugging
# fast_dev_run = true
